name: Action Runner Demo

env:
  LATEST_TAG: chuangw/hello-runner:latest

on: [push]

jobs:
  Say-hello:
    runs-on: self-hosted
    strategy:
      matrix:
        greeting: ["chuang", "daniel", "trevor"]
    steps:
      - run: echo "Hello ${{ matrix.greeting }} from self-hosted runner"

  Build-docker-image:
    runs-on: self-hosted
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.LATEST_TAG }}
