name: Action Runner Demo

on: [push]

jobs:
  Say-hello:
    runs-on: self-hosted
    strategy:
      matrix:
        greeting: ["chuang", "daniel", "trevor"]
    steps:
      - run: echo "Hello ${{ matrix.greeting }} from self-hosted runner"
